fetch("https://raw.githubusercontent.com/cvius/all-of-artist-x/main/allOfArtistX.js")
    .then(res => res.text())
    .then(content => new Blob([content], { type: "application/javascript" }))
    .then(URL.createObjectURL)
    .then(url => import(url))
